"use client";

import { useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { formatWhen, loadStudioState, type StudioState } from "../lib/studio";
const EMPTY: StudioState = { computers: [], software: [], plugins: [], endpoints: [], connections: [], observations: [], gear: [], documents: [], document_entities: [] };
function Status({ children, kind = "unknown" }: { children: React.ReactNode; kind?: string }) { return <span className={`status status-${kind}`}>{children}</span>; }
function Metric({ value, label, tone }: { value: string | number; label: string; tone?: string }) { return <div className={`metric ${tone || ""}`}><b>{value}</b><span>{label}</span></div>; }

export function StudioOverview({ client }: { client: SupabaseClient }) {
  const [state, setState] = useState<StudioState>(EMPTY); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { loadStudioState(client).then(setState).catch((e) => setError(String(e.message || e))).finally(() => setLoading(false)); }, [client]);
  const latestObservation = useMemo(() => [...state.observations].sort((a, b) => String(b.observed_at).localeCompare(String(a.observed_at)))[0], [state.observations]);
  const defaultIn = state.endpoints.find((e) => e.is_default_input); const defaultOut = state.endpoints.find((e) => e.is_default_output);
  const rateSplit = defaultIn?.sample_rate_hz && defaultOut?.sample_rate_hz && defaultIn.sample_rate_hz !== defaultOut.sample_rate_hz;
  if (loading) return <div className="card"><p className="tag">Loading studio evidence…</p></div>;
  if (error) return <div className="card"><p className="err">Could not load studio state: {error}</p></div>;
  return <>
    <section className="hero-panel cockpit-hero"><div><div className="eyebrow">STUDIO COCKPIT</div><h2>Know what is true before changing what is physical.</h2><p>Live observations, saved configuration, documentation and unknowns remain visibly separate. Browser hardware control is intentionally absent.</p></div><div className="hero-status"><Status kind="observed">session data loaded</Status><span className="tag">latest observation · {formatWhen(latestObservation?.observed_at)}</span></div></section>
    <section className="evidence-legend" aria-label="Evidence states"><Status kind="observed">Observed</Status><Status kind="user-live">User-reported live</Status><Status kind="documented">Documented</Status><Status kind="configured">Configured</Status><Status kind="planned">Planned</Status><Status kind="unknown">Unknown</Status></section>
    <div className="metrics cockpit-metrics"><Metric value={state.endpoints.length} label="observed endpoints" tone="metric-observed" /><Metric value={state.connections.length} label="physical routes recorded" tone={state.connections.length ? "metric-configured" : "metric-unknown"} /><Metric value={state.documents.length} label="knowledge sources" /><Metric value={state.document_entities.length} label="document → gear edges" /><Metric value={state.gear.length} label="gear records" /></div>
    {state.connections.length === 0 && <div className="callout truth-callout"><strong>Physical routing remains unknown.</strong> Document relationships and inventory records are not being promoted into cable or MIDI-route facts.</div>}
    <section className="card topology-card"><div className="section-head"><div><div className="eyebrow">TRUTH TOPOLOGY</div><h3>Observed computer → observed endpoints → unresolved physical studio</h3></div><Status kind={state.connections.length ? "configured" : "unknown"}>{state.connections.length ? `${state.connections.length} recorded routes` : "acceptance evidence required"}</Status></div><div className="topology-grid"><div className="topology-lane"><span className="lane-label">OBSERVED COMPUTER</span>{state.computers.map((c) => <div className="node node-computer" key={c.id}><strong>{c.name}</strong><span>{c.hardware_model}</span><small>{c.platform} {c.os_version}</small></div>)}</div><div className="topology-arrow topology-solid">→</div><div className="topology-lane"><span className="lane-label">OBSERVED ENDPOINTS</span>{state.endpoints.map((e) => <div className="node node-endpoint" key={e.id}><strong>{e.name}</strong><span>{e.endpoint_type} · {e.transport}</span><small>{e.sample_rate_hz ? `${Number(e.sample_rate_hz) / 1000} kHz` : e.direction || "observed"}</small></div>)}</div><div className="topology-arrow topology-unknown">{state.connections.length ? "→" : "···?"}</div><div className="topology-lane"><span className="lane-label">GEAR INVENTORY · NOT A ROUTE MAP</span>{state.gear.slice(0, 8).map((g) => <div className="node node-gear" key={g.id}><strong>{g.make} {g.model}</strong><span>{g.category}</span></div>)}{state.gear.length > 8 && <small className="tag">+ {state.gear.length - 8} more in Rig</small>}</div></div></section>
    <div className="split-grid"><section className="card"><div className="section-head"><h3>Observed operating state</h3><Status kind="observed">observed</Status></div>{state.software.map((s) => <div className="state-row" key={s.id}><span>{s.name}</span><b>{s.version || "version unknown"}</b></div>)}{defaultIn && <div className="state-row"><span>Default input</span><b>{defaultIn.name} · {Number(defaultIn.sample_rate_hz) / 1000} kHz</b></div>}{defaultOut && <div className="state-row"><span>Default output</span><b>{defaultOut.name} · {Number(defaultOut.sample_rate_hz) / 1000} kHz</b></div>}{rateSplit && <div className="callout warn-callout">Input/output sample rates differ. Review before a critical recording session.</div>}</section><section className="card"><div className="section-head"><h3>Evidence inventory</h3><Status kind="documented">mixed evidence</Status></div><div className="state-row"><span>Documents</span><b>{state.documents.length}</b></div><div className="state-row"><span>Observations</span><b>{state.observations.length}</b></div><div className="state-row"><span>Connections</span><b>{state.connections.length || "none recorded"}</b></div><div className="state-row"><span>Plugin records</span><b>{state.plugins.length}</b></div><p className="note">Counts describe stored records. They do not establish current physical state unless backed by an observation.</p></section></div>
    <section className="card"><div className="section-head"><h3>Recent evidence</h3><span className="tag">newest first</span></div><div className="observation-list">{[...state.observations].sort((a,b) => String(b.observed_at).localeCompare(String(a.observed_at))).slice(0,6).map((o) => <div className="observation" key={o.id}><Status kind={o.evidence_type === "live_observation" ? "observed" : "documented"}>{o.evidence_type}</Status><div><strong>{o.fact_key.replaceAll("_", " ")}</strong><p>{o.source_ref || o.notes || "source recorded"}</p></div><time>{formatWhen(o.observed_at)}</time></div>)}</div></section>
  </>;
}
